openapi: "3.0.0"
info:
  version: 1.0.0
  title: People API
servers:
  - url: http://localhost:8080
paths:
  /people:
    post:
      summary: post people
      operationId: postPeople
      tags:
        - people
      requestBody:
        description: Create a new people
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeopleRequest'
      responses:
        '200':
          description: Get People
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PeopleResponse"
    get:
      summary: get people
      operationId: getPeople
      tags:
        - people
      responses:
        '200':
          description: Get People
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PeopleResponse"
components:
  schemas:
    PeopleRequest:
      required:
        - name
        - age
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
    PeopleResponse:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32